### ISSUE TITLE
'git status' Command?

### ISSUE THREAD

**Issue by garymh** [camspiers/snap#10]
Hi @camspiers ! I love how fast this is!

I'm trying to figure out if a list of files from the command "git status" is possible. I've tried this:

```lua
snap.register.map({'n'}, {'<space>g'}, function()
    snap.run({
        prompt = '❯',
        producer = fzy(snap.get'producer.git.general'.args {"--status"}),
        select = select_file.select,
        multiselect = select_file.multiselect
    })
end)
```

Am I on the right track?

**Comment by camspiers** [comment]
There isn't an ability to pass arbitrary args to general yet but a status producer would look like this:

```
(let [snap (require :snap)
      general (snap.get :producer.git.general)]
  (fn [request]
    (let [cwd (snap.sync vim.fn.getcwd)]
      (general request {:args [:status :--porcelain] : cwd}))))
```

However you need to modify each result to remove the leading 3-4 chars (can't remember if it is 3 or 4).

I can help with this probably at some time today.
