### ISSUE TITLE
Toggle preview window

### ISSUE THREAD

**Issue by ahmedelgabri** [camspiers/snap#12]
I work in a very big monorepo & it's very common to have files +8 folders deep & duplicate names, which doesn't usually fit in the search results window. What I liked about `fzf` + `fzf.vim` was the ability to toggle the preview window so I can see the full path when I get multiple matching results. So it will be great if there is an option to do that on the fly.

**Comment by camspiers** [comment]
Added in https://github.com/camspiers/snap/commit/c9d6dcc516d096f022bd30d0bb2640a3253d44ea

Use <C-h>

**Comment by camspiers** [comment]
@ahmedelgabri 😊

**Comment by YodaEmbedding** [comment]
- Can the `C-h` persist (for a given view) for the remainder of the vim session?
 - Can this be made permanent?
 - Can the preview hiding behavior be auto-detected? My terminal sometimes has a width of 80 characters, which is too small to preview.
 - Perhaps a more general way to handle the above is to choose different layouts depending on window dimensions. That way, the preview window may even be placed at the top when the terminal is too narrow.

**Comment by gegoune** [comment]
I am not sure if that is still the case but when I first tested snap I noticed that it wasn't possible to enable preview (configure it) but don't show by default, making it show only on demand by `<C-h>`. I barely ever need previews for buffers, files, etc, but would like to be able to peek in when needed.

**Comment by camspiers** [comment]
I will add the option to default to off to the new configuration API, and add auto detect for small terminal sizes

**Comment by camspiers** [comment]
See #42 for the new work on the configuration API. It will land probably this weekend.
