### ISSUE TITLE
File selections should return absolute paths

### ISSUE THREAD

**Issue by ahmedelgabri** [camspiers/snap#13]
While trying to write a custom function I realized that general producers will return relative paths to the `cwd` & not absolute paths. Which makes writing anything custom that searches in a specific directory impossible. Not sure if this issue is related to #8 because I also got "no such file or directory" error.

```lua
local snap = require "snap"
local M = {}

local fzf = snap.get "consumer.fzf"
local preview_vimgrep = snap.get "preview.vimgrep"
local general_rg = snap.get("producer.ripgrep.general")


local function notes(request)
  return general_rg(
    request,
    {
      args = {"--line-buffered", "--files"},
      cwd = snap.sync(string.format('%s/Sync/notes', os.getenv('HOME')))
    }
  )
end

function M.search_notes()
  snap.run(
    {
      prompt = "",
      producer = fzf(notes),
      select = select_file.select,
      multiselect = select_file.multiselect,
      views = {preview_vimgrep}
    }
  )
end
```

<s>Right now all general producers return https://github.com/camspiers/snap/blob/bdcb3753d2cc47b62b3715214703face24c7267e/fnl/snap/producer/ripgrep/general.fnl#L12

So when I select a file it will try to open the path relative to my `cwd` & not relative to the `cwd` in the general call (which requires the full path so you can use it from anywhere)

Instead, maybe they should return something like this

```lua
coroutine.yield(
  vim.tbl_map(
    function(file)
      return string.format("%s/%s", cwd, file)
    end,
    vim.split(data:sub(1, -2), "\n", true)
  )
)
```

But… that will surface another problem, you don't want to show the full path in the search result window. But I'm not sure how to tackle that.</s>

Edit: Looking at this again, I wonder if this should be solved with a custom select & maybe I missed that? 🤔 

Edit2: Custom selection is the solution but I think that should be handled by snap, because the only difference is that I'm resolving the full path.

```lua
select = function(selection, winnr, type)
  local buffer = vim.fn.bufnr(string.format("%s/%s", string.format('%s/Sync/notes', os.getenv('HOME'), tostring(selection)), true)
  vim.api.nvim_buf_set_option(buffer, "buflisted", true)

  if (type == nil) then
    if (winnr ~= false) then
      return vim.api.nvim_win_set_buf(winnr, buffer)
    end
  elseif (type == "vsplit") then
    vim.api.nvim_command("vsplit")
    return vim.api.nvim_win_set_buf(0, buffer)
  elseif (type == "split") then
    vim.api.nvim_command("split")
    return vim.api.nvim_win_set_buf(0, buffer)
  elseif (type == "tab") then
    vim.api.nvim_command("tabnew")
    return vim.api.nvim_win_set_buf(0, buffer)
  end
end
```

But now the second problem I can't find a solution for is "no such file or directory" error.

**Comment by camspiers** [comment]
I believe this is resolved in https://github.com/camspiers/snap/commit/f170902e1a9f249731970e90407176c2234f4668

You can now pass a cwd to `ripgrep.file.args` and it will make paths for that search absolute. See: https://github.com/camspiers/snap#search-files-in-multiple-paths

**Comment by ahmedelgabri** [comment]
I'm still struggling to get my custom search working (doesn't return any results, the search panel is empty)

```lua
local function notes(request)
  return snap.get "producer.ripgrep.general"(
    request,
    {
      args = {"--line-buffered", "-M", "100", "--vimgrep", request.filter},
      cwd = snap.sync(os.getenv("NOTES_DIR"))
    }
  )
end

snap.register.map(
  {"n"},
  {"<localleader>sn"},
  function()
    snap.run {
      producer = snap.get "consumer.fzf"(notes),
      select = snap.get "select.vimgrep".select,
      multiselect = snap.get "select.vimgrep".multiselect,
      views = {snap.get "preview.vimgrep"},
      -- initial_filter = vim.fn.expand("<cword>"),
      mappings = custom_mappings
    }
  end
)
```


& even this example throws errors for me

```lua
snap.run {
  producer = snap.get'producer.ripgrep.vimgrep',
  steps = {{
    consumer = snap.get'consumer.fzf',
    config = {prompt = "FZF>"}
  }},
  select = snap.get'select.file'.select,
  multiselect = snap.get'select.file'.multiselect,
  views = {snap.get'preview.file'}
}
```


https://user-images.githubusercontent.com/63876/122820706-32b08780-d2dc-11eb-8df1-a653a59ad37f.mp4

**Comment by ahmedelgabri** [comment]
Ignore my last comment, the issue was on my side, `snap.sync` needs a function not a string. This works now

```lua
local notes_producer =
  snap.get "consumer.limit"(
  50000,
  function(request)
    return snap.get "producer.ripgrep.general"(
      request,
      {
        absolute = true, -- also this is needed
        args = {
          "--line-buffered",
          "-M",
          "100",
          "--vimgrep",
          request.filter
        },
        cwd = snap.sync(function() return os.getenv("NOTES_DIR") end)
      }
    )
  end
)
```
