### ISSUE TITLE
Snap opening files from one path inside two instances of neovim

### ISSUE THREAD

**Issue by ahmedelgabri** [camspiers/snap#15]
The left side is my dotfiles repo & right side is my fork of snap, notice that I try to open `.gitattributes` file in both & snap opens the one from the snap fork. Although both of them are different (you can clearly see the contents in the preview)

Not sure what's happening here.

https://user-images.githubusercontent.com/63876/121737462-2fa5e200-caf9-11eb-84f0-12914fdc3fa4.mp4

**Comment by camspiers** [comment]
I can't reproduce this, I think it is fixed.
