### ISSUE TITLE
How to scroll in the preview window?

### ISSUE THREAD

**Issue by sandangel** [camspiers/snap#20]
Hi, I would like to scroll in the preview window, how can I add the keymap for that?

**Comment by camspiers** [comment]
It's in the docs: https://github.com/camspiers/snap#view-page-down

<C-d> and <C-u>

**Comment by sandangel** [comment]
hi @camspiers , sorry I also realize that. I would like to ask how can we remap the Preview key bindings? can it accept/reuse the FZF options in the environment variables?
