### ISSUE TITLE
How to make snap fall back to file searching from a git search?

### ISSUE THREAD

**Issue by babygau** [camspiers/snap#26]
Hi, 
I'm wondering if it is possible to make _snap_ automatically fall back to file searching if the working dir is not  _git_ project.

**Comment by camspiers** [comment]
That is a good question, I think it should be fairly simple it introduce two new consumers, one a combination consumer and the other a conditional consumer:

combine(producer1, producer2)

And:

try(producer1, producer2)

Combine would just combine the results of two or more producers, and try would use the first, then if no results occur will try the second, and then the third if provided etc.

Thanks for the ideas!

**Comment by camspiers** [comment]
Resolved in https://github.com/camspiers/snap/commit/e19696700a6188cc145ba587de131195d1731fc8

You can now do something like:

```lua
snap.run {
  producer = snap.get'consumer.fzf'(
    snap.get'consumer.try'(
      snap.get'producer.git.file',
      snap.get'producer.ripgrep.file'
    ),
  ),
  select = snap.get'select.file'.select,
  multiselect = snap.get'select.file'.multiselect,
  views = {snap.get'preview.file'}
}
```

**Comment by camspiers** [comment]
I hope this example also helps to illustrate the flexibility of the producer consumer pattern.

**Comment by babygau** [comment]
Wow, that's great. I really like the `try` and `combine` idea. Cheers!
