### ISSUE TITLE
"Ignore current buffer" setting for buffer producer

### ISSUE THREAD

**Issue by garymh** [camspiers/snap#28]
Thought of another feature request 😄:

The buffers listing command is great, but I have some muscle memory with FZF/Telescope where the buffers list ignores the current buffer you're in. I've been using this as a psuedo `<c-^>`. since the next buffer is the most recently used buffer (although that might not be the case in snap).

I've been playing with ways to do this with `vim.api.nvim_get_current_buf()`, but I think snap's UI is counting as a buffer which throws off any possible conditionals.

**Comment by camspiers** [comment]
You can access the current buffer using the winnr property that is on the request. Omitting the vim.fn because I'm on my phone:

```
bufname(winbufnr(request.winnr))
```

**Comment by camspiers** [comment]
See https://github.com/camspiers/snap/issues/27

**Comment by camspiers** [comment]
With:

https://github.com/camspiers/snap/commit/5c32028129f4fff3a7e4207350885a88bbec8c6e

and:

https://github.com/camspiers/snap/commit/76b136f05081aadbc9163de06ecf4c9146f7f5a3

You can now do arbitrary filtering:

```lua
snap.run {
  producer = snap.get'consumer.fzy'(
    snap.get'consumer.filter'(
      function (request, result)
        -- return boolean, if true then result is added, otherwise it is filtered
      end,
      snap.get'producer.vim.buffer'
    ),
  ),
  select = snap.get'select.file'.select,
  multiselect = snap.get'select.file'.multiselect,
  views = {snap.get'preview.file'}
}
```

**Comment by garymh** [comment]
Awesome! Thank you!!
