### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by TyberiusPrime** [camspiers/snap#34]
My snap windows look like this
![image](https://user-images.githubusercontent.com/1257580/122730404-770b3b80-d27a-11eb-9aac-41108eb72572.png)

That's very distracting. I'd like for the non-selected lines too look a lot more subtle. 
I could even live without any highlights :).

I found it uses the IncSearch highlight for this, and e.g.
```highlight IncSearch guibg='#1a2b36' guifg='NONE' gui=bold```
adjust its

But now of course all my search highlights are also subtle and kinda hard to see.

Perhaps I could rig something with BufEnter/BufLeave just for snap?

**Comment by zetashift** [comment]
I kind have a similiar request, in that I want the current selected one to be more noticable, here is my view, I can't really notice the matching highlights
![image](https://user-images.githubusercontent.com/1857826/122788964-1e0dc880-d2b7-11eb-9386-bb6918bfcc2e.png)

**Comment by saadparwaiz1** [comment]
You can configure all of these by changing the following `highlights` heres's what I use for gruvbox:

```vim
highlight! link SnapSelect GruvboxBlue
highlight! link SnapMultiSelect GruvboxGray
highlight! link SnapNormal GruvboxFg1
highlight! link SnapBorder SnapNormal
highlight! link SnapPrompt GruvboxOrangeBold
highlight! link SnapPosition GruvboxOrangeBold 
```

which looks as follows:

![Screenshot 2021-06-21 at 17 58 31](https://user-images.githubusercontent.com/73385353/122800005-56fb6c80-d2ba-11eb-8bf8-cc153a71cbc3.jpg)

**Comment by camspiers** [comment]
It sounds like it still needs some improvement. Thanks for the report

**Comment by TyberiusPrime** [comment]
Thanks, I had missed #9.
I have to stick it into an autocmd at BufEnter though - might be my config...
