### ISSUE TITLE
README potentially out of sync with code

### ISSUE THREAD

**Issue by wbthomason** [camspiers/snap#39]
First off, thanks for making this - it seems excitingly fast, and I'm a big fan of the design.

I think the recently updated README has a bit of a bug - the global keymap examples now pass strings rather than tables for the mode and list of keys to bind, but this gives an error at https://github.com/camspiers/snap/blob/bc78b327b5df25d4abbc5302a34de816f8897239/lua/snap/common/register.lua#L172

Looking at the Fennel, maybe you just need to recompile to Lua? It seems like `handle-strings` should account for this issue.

**Comment by camspiers** [comment]
Fixed in: https://github.com/camspiers/snap/commit/7a61088e614322ea9077cb59d20c18fbd539550d

Thanks!

**Comment by camspiers** [comment]
For posterity, and for anyone who stumbles on this before I update the docs with the API for snap.register.map, you can pass either a table of modes of just a mode string, and you can pass either a table of mappings or a single mapping as a string.
