### ISSUE TITLE
System locks up when using limit with fzf

### ISSUE THREAD

**Issue by akinsho** [camspiers/snap#4]
Hi 👋🏾 thanks for your work on this, it's really impressive.

I've just been trying to tweak the grep functionality to have some fuzzy behaviour/see how it works and just had my system hang had to kill the nvim process using the following config.

```lua

    use {
      "camspiers/snap",
      rocks = {"fzy"},
      config = function()
        local snap = require("snap")
        local limit = snap.get("consumer.limit")
        local fzf = snap.get("consumer.fzf")
        snap.register.map(
          {"n"},
          {"<leader>fs"},
          function()
            snap.run {
              prompt = "Grep",
              producer = fzf(
                limit(10000, snap.get("producer.ripgrep.vimgrep")) -- <-- this seems like the issue
              ),
              select = snap.get("select.vimgrep").select,
              multiselect = snap.get("select.vimgrep").multiselect,
              views = {snap.get("preview.vimgrep")}
            }
          end
        )
      end
    }

```

I might be using things incorrectly since I don't see an example of using the limit as well as the `fzf` consumer, was just trying to see how they can be used together.

**Comment by camspiers** [comment]
I will have to look into this further, thanks for the report, but the first note is that it doesn't make sense to use the `ripgrep.vimgrep` producer with the `fzf` or `fzy` consumer added. vimgrep is already filtering because it's grepping text, and as such further filtering the input via fzf or fzy is probably not going to give you what you want. I suggest removing the fzf consumer in this case and instead just use `ripgrep.vimgrep`. If you need to use regular expressions etc in ripgrep you can. Closing for now, but reopen if this didn't address the issue as thing locking up is not what I want :D

**Comment by akinsho** [comment]
@camspiers thanks for clearing things up. I realised my mistake but raised it anyway because the side effect of making this mistake is quite dramatic. Regarding `ripgrep.vimgrep` what I was initially trying to do was replicate, fzf.vim's `Rg` function which allows you to fuzzy find a string across a project. using the `ripgrep.vimgrep` produce doesn't quite do the same thing since the results from `rg` aren't can't then be filtered using fzf?

I could very easily be missing something conceptually. Is there a way to fuzzy find a string in the cwd?

**Comment by camspiers** [comment]
I guess I don't quite understand the feature request, the syntaxes for ripgrep and fzf syntax are different, so it doesn't make sure to me that the same input prompt would drive both the ripgrep query and the fzf fuzzy filtering. I think the right approach conceptually here is to have two input fields, one for the ripgrep query and one for the fzf filtering. But I need to think through the sense of that, the same idea came up in the following reddit thread too, so I guess it is a common desire.

https://www.reddit.com/r/neovim/comments/nvl2fy/snap_a_nonblocking_finder_system_for_neovim_05/h1bqqll/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by camspiers** [comment]
Maybe the concept is like a secondary consumer, if the secondary consumer is provided the a secondary input appears, if the secondary input has content, then the secondary consumer will be be passed the primary producer as an input and take over the results buffer so you can filter further. Unsure.

**Comment by camspiers** [comment]
https://github.com/camspiers/snap/commit/dd9e742b9c095a8a615c26b949b7aab00bb87359

I think you will like this feature.

You can now run:

```
  (snap.register.map
    [:n]
    [:<Leader>ff]
    (fn []
      (snap.run {:prompt :Grep
                 :producer (limit 50000 producer-vimgrep)
                 :next {:consumer fzf :config {:prompt :FZF}}
                 :select select-vimgrep.select
                 :multiselect select-vimgrep.multiselect
                 :views [preview-vimgrep]})))
```

And you can change arbitrary config for the next consumer. Then next consumer get provided the current results list from the results view.

This supports any kind of chaining you want.

To activate the the next consumer/config just hit <C-q> for any results view you have (provided you have configured `next`).

**Comment by akinsho** [comment]
@camspiers just tried it out but can't quite get it working but need to probably spend a bit more time with it.

I've configured it as
```lua
    use {
      "camspiers/snap",
      rocks = {"fzy"},
      -- branch = "fixes/lsp-preview",
      config = function()
        local snap = require("snap")
        local limit = snap.get("consumer.limit")
        local vimgrep = snap.get("select.vimgrep")
        local fzf = snap.get("consumer.fzf")
        print("fzf: " .. vim.inspect(fzf))
        snap.register.map(
          {"n"},
          {"<leader>fs"},
          function()
            snap.run {
              prompt = "Grep",
              producer = limit(10000, snap.get("producer.ripgrep.vimgrep")),
              ["next"] = {fzf({config = {prompt = "FZF"}})},
              select = vimgrep.select,
              multiselect = vimgrep.multiselect,
              views = {snap.get("preview.vimgrep")}
            }
          end
        )
      end
    }

```

The FZF thing I was talking about is
```
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case -- %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)
```
from [here](https://github.com/junegunn/fzf.vim#example-rg-command-with-preview-window)

I don't know about needing multiple inputs or anything or if this implementation requires that somehow. I'll be honest and say I never dug into how fzf was using ripgrep to do the grepping if things were being piped together etc.#5 
I'll spend a bit more time with it once I get a chance

**Comment by akinsho** [comment]
Tbh I hadn't really meant this as a feature request although it's definitely nice to have. If you get the chance I think it's worth trying `fzf.vim`'s `Rg` command to see how the flow works. No pressure to implement this straight away since this isn't really what I was driving at.

Using `:Rg` from fzf, there is no visible secondary input or further user input required. Say I'm looking for `fill_line` in my repo and I typed `flne` after hitting `Rg` that would just immediately surface the function as part of the result.

**Comment by camspiers** [comment]
next should be:

```
{consumer = fzf, config = {prompt = "FZF>"}}
```
