### ISSUE TITLE
hang / pause: Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by alxndr** [camspiers/snap#45]
I used a [mapping added with `snap.register.map`](https://github.com/alxndr/dotfiles/blob/122e6b8d64c8342a6d35ff2e1ffc3592a3e21b0e/nvim/init.lua#L59-L66) and then typed ~9 chars very quickly, my CPU lit up and the Neovim UI seemed to be frozen and showed this in the status bar:

```Error executing vim.schedule lua callback: ...m/site/pack/paqs/start/snap/lua/snap/producer/create.lua:48: Invalid buffer id: 32```

After ~30 sec the message disappeared and the UI was responsive. I was then able to use the same mapping and look for a file using the same (?) 9 characters from earlier.

**Comment by alxndr** [comment]
Got it again, this time the error message said `Invalid buffer id: 528`

**Comment by camspiers** [comment]
Can you try again after? I have made some big changes recently. If you still get the issue can you point me to a repo and config it reproduces on and I can try debug, otherwise it is hard to repro because I haven't encountered this error locally.

**Comment by camspiers** [comment]
Also check out the new config API: https://github.com/camspiers/snap/pull/42
