### ISSUE TITLE
Include untracked files in git files 

### ISSUE THREAD

**Issue by beauwilliams** [camspiers/snap#48]
Putting this here in case anyone else is interested in this too

**Comment by YodaEmbedding** [comment]
Similarly, also show untracked hidden files that are not .gitignore'd. (This should also apply to `producer.fd.file`.)

**Comment by beauwilliams** [comment]
That should be doable. I might see if I have time later to improve my PR. 

fd.file, shouldnt that show files regardless of git?

**Comment by beauwilliams** [comment]
> Similarly, also show untracked hidden files that are not .gitignore'd. (This should also apply to `producer.fd.file`.)

This should be fixed in my branch. We can see here hidden and untracked files are showing. 

There is no option with git ls-files to not show hidden files. They display by default and you can not hide them afaik.

![image](https://i.ibb.co/123xCpw/Screen-Shot-2021-06-27-at-10-39-28-am.png)

**Comment by yujinyuz** [comment]
I think this is a similar issue #62 

You can now include untracked files in git by passing extra arguments to git file. I have this in my config

```lua
snap.maps {
  {
    '<leader><leader>', file {
      try = {
        snap.get('producer.git.file').args({'--cached', '--others', '--exclude-standard'}),
        'ripgrep.file',
      },
      prompt = 'Files',
    },
  },
}
```

**Comment by beauwilliams** [comment]
Perfect 😃 Thanks for the heads up
