### ISSUE TITLE
ENOENT: no such file or directory error, whilst using the files picker

### ISSUE THREAD

**Issue by akinsho** [camspiers/snap#49]
Occasionally whilst using the file picker, it errors saying that a particular directory couldn't be found. In the case in this example, the file used to exist but was deleted. I'm not sure why snap still has a reference to it.

![Screen Shot 2021-06-24 at 14 25 40](https://user-images.githubusercontent.com/22454918/123271044-56e8b000-d4f8-11eb-9e46-85a663b9d879.png)

Other instances of this issue involve snap having a reference to the incomplete file path e.g.
https://github.com/camspiers/snap/issues/6#issuecomment-866580309 where the file's extension is missing some characters and this error occurs

**Comment by akinsho** [comment]
A little more information to potentially help debug this information
<img width="1433" alt="Screen Shot 2021-06-24 at 16 29 11" src="https://user-images.githubusercontent.com/22454918/123290849-7fc57100-d509-11eb-8dcd-4c201cae0b6b.png">

I found in a particular work project I was able to reproduce this issue consistently by just entering `.`, into the prompt. If you look closely the paths of the results have been truncated somehow and I'm guessing snap tries to open these files only to find that they don't exist

**Comment by beauwilliams** [comment]
I have a similar issue where end of file extension gets cut off occasionally

![image](https://i.ibb.co/qspsQbg/Screen-Shot-2021-06-25-at-5-52-38-pm.png)

**Comment by camspiers** [comment]
Can you try shifting to the `fzy` consumer instead of `fzf`? this will help me determine if it is `fzf` that is causing it.

**Comment by babygau** [comment]
I could confirm this only happened with `fzf` only, found no issue with `fzy` so far

**Comment by akinsho** [comment]
I've switched to `fzy` and will report back since for me the issue is sporadic, or whatever I'm doing to trigger it isn't clear to me, but so far so good.

**Comment by ahmedelgabri** [comment]
I can reproduce this always using this example https://github.com/camspiers/snap#grep-with-fzf-as-optional-next-step which uses `fzf` I will try with `fzy` & see.

**Comment by akinsho** [comment]
I've had a few episodes whilst also using `fzy`, in one example I can reproduce the issue seems to be that whilst using `vim.buffer` I have a log buffer which doesn't exist on my system i.e. it's a scratch buffer with a buftype of `nofile`. When I try and select it to open in snap, it throws the file doesn't exist error.

```
...re/nvim/site/pack/packer/opt/snap/lua/snap/common/io.lua:136: ENOENT: no such file or directory: /<my-dir>/a-project/DEV_LOG__
```

**Comment by yujinyuz** [comment]
So far I only experience this when I'm using `git.file` as producer. Is it the same for anybody else?

**Comment by camspiers** [comment]
Closed with https://github.com/camspiers/snap/commit/ac6ad973589bb74eb15f11219b840f7080e4ed33
