### ISSUE TITLE
Run external commands as input

### ISSUE THREAD

**Issue by babygau** [camspiers/snap#60]
Let's say I have the following external command which return an FZF result of note's path

`rg title: | cut -d ' ' -f2- | fzf`

Is it possible to use it with `snap`?

**Comment by saadparwaiz1** [comment]
There is a [snippet](https://github.com/camspiers/snap#how-snap-works) in readme that shows how to use `ls` with snap. You can adapt it to use your command.

**Comment by babygau** [comment]
Thank you! Somehow I overlooked that section.
