### ISSUE TITLE
Pass arguments to git.file with try fallback

### ISSUE THREAD

**Issue by yujinyuz** [camspiers/snap#62]
I currently have this in my config

```
  local snap = require('snap')
  local file = snap.config.file:with{reverse = false, consumer = 'fzf'}
  local vimgrep = snap.config.vimgrep:with{
    reverse = false,
    consumer = 'fzf',
    limit = 50000,
  }

snap.maps {
  {'<leader>ss', file {prompt = 'Files', try = {'git.file', 'ripgrep.file'}}}
}
```

How can I pass arguments to `git.file`?

```
git ls-files --cached --others --exclude-standard
```

**Comment by babygau** [comment]
@yujinyuz you can take reference from [here](https://github.com/camspiers/snap/pull/42#issuecomment-868977057)

**Comment by yujinyuz** [comment]
@babygau thanks. I just tried it but I get this error

```
packer.nvim: Error running config for snap: [string "..."]:0: attempt to index a function value
```

**Comment by camspiers** [comment]
I don't think `git.file` supports adding arbitrary arguments yet, though it should. I can take a look

**Comment by camspiers** [comment]
Closed in: https://github.com/camspiers/snap/commit/2da8617c4a292fefa9d60320ed3667c4cbd0780c

**Comment by yujinyuz** [comment]
Thanks.

Does this mean I have to also include `ls-files` to the args? Something like tihs?

```lua
snap.maps {
        {
          '<leader>ss', file {
            try = {
              snap.get'producer.git.file'.args({'ls-files', '--cached', '--others'}),
              'ripgrep.file',
            }
          },
        },
```

**Comment by camspiers** [comment]
ls-files should be defaulted in and you are just adding the extras. Thanks for logging the issue btw!

**Comment by yujinyuz** [comment]
@camspiers Welcome! Also thanks for the immediate fix for this
