### ISSUE TITLE
Freeze on VimResized

### ISSUE THREAD

**Issue by vanhtuan0409** [camspiers/snap#63]
Hi, I notice that Snap might cause nvim to freeze for a brief of time (maybe up to 1s) upon terminal resize event, even if Snap is not opened
Disable Snap and the problem is resolved
Hope anyone can shed some light on this

**Comment by camspiers** [comment]
Hmm, definitely a bug. Thanks

**Comment by camspiers** [comment]
Fixed in https://github.com/camspiers/snap/commit/1fbd674dc53401fd643a2bb8bf07dd3e7125d430
