### ISSUE TITLE
`preview = true` not working for ripgrep.file and vimgrep

### ISSUE THREAD

**Issue by zetashift** [camspiers/snap#74]
Using this in my config(also 99% based off your config camspiers):

```clojure
(snap.config.file:with { :preview true :consumer :fzf :layout layout.bottom :suffix :» }))
(snap.config.vimgrep:with { :layout layout.bottom :limit 50000 :suffix :» }))


  (snap.maps [

    [:<Leader><Leader> (file {:prompt "Find files" :producer :ripgrep.file : args}) {:command :find-files}]

    [:<Leader>fg (file {:prompt "Search Git Files" :producer :git.file}) {:command :git.files}]

    [:<Leader>ff (vimgrep {:prompt "Find in files"}) {:command :grep}]])

```

However there are no previews being shown?
![image](https://user-images.githubusercontent.com/1857826/125134956-81498880-e108-11eb-88fc-35b4f3cc6b40.png)

EDIT: `file` is correctly installed and when I make a custom `map` with a customer `preview.vimgrep` a preview window is being shown!

**Comment by zetashift** [comment]
If I do `<C-h>` then it does show the preview, it just doesn't persist/does it automatically:
![image](https://user-images.githubusercontent.com/1857826/125139801-7e06ca80-e111-11eb-9d1f-2cd2263e8126.png)

Also another noobie question but is there anyway to get consistent (treesitter) highlighting in the preview?

**Comment by mactep** [comment]
I'm facing the same issue. The worked it out using those `snap.run` calls instead of the default ones, although I would prefer using the default version.

**Comment by mactep** [comment]
I just discovered that setting `preview_min_width` to a low value, say 0, brings the preview back. Maybe the threshold is too high?

**Comment by camspiers** [comment]
the preview_min_width by default is set so that you must be able to see 80 cols for both the results view and preview view.
