### ISSUE TITLE
[QUESTION] Why should I use this plugin over telescope.nvim ?

### ISSUE THREAD

**Issue by marcelarie** [camspiers/snap#89]
I think there is no information about this on the README.
Of course, I can see that it is much more configurable and arguably has a better API, but I would like to know if there are any other gains.

Thanks!

**Comment by camspiers** [comment]
It was created originally because I was facing performance in using telescope particularly when using live_grep. 

Some context in: https://www.reddit.com/r/neovim/comments/nvl2fy/snap_a_nonblocking_finder_system_for_neovim_05/

**Comment by marcelarie** [comment]
Gotcha, thanks for the reply!
